"""
141 bevestigde laadpaal-adressen in Vathorst (bron: Plan Vathorst.docx).

Elk adres is GROUND TRUTH: Mattijs heeft persoonlijk bevestigd dat er
een laadpaal aan de gevel of op de oprit staat. De POC test dus:
  - hoe vaak Gemini deze correct als "heeft laadpaal" identificeert
  - false-negative-rate (verwacht doel: <15%)

Voor false-positive-test hebben we later ook een controlegroep nodig
(bijv. appartementen zonder oprit).
"""

TEST_ADDRESSES = [
    {"adres": "Straat van Gibraltar 32, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Gibraltar 28, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Gibraltar 26, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Gibraltar 12, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Gibraltar 170, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Gibraltar 110, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Gibraltar 112, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Gibraltar 100, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 116, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 114, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 109, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 90, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 82, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 74, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 72, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 48, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 40, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 36, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Dover 20, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Messina 31, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Messina 49a, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Messina 6, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Messina 57, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Messina 8, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Messina 10, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Messina 81, Amersfoort", "expected_has_charger": True},
    {"adres": "Straat van Messina 14f, Amersfoort", "expected_has_charger": True},
    {"adres": "Drontermeer 8, Amersfoort", "expected_has_charger": True},
    {"adres": "Drontermeer 63, Amersfoort", "expected_has_charger": True},
    {"adres": "Drontermeer 57, Amersfoort", "expected_has_charger": True},
    {"adres": "Drontermeer 31, Amersfoort", "expected_has_charger": True},
    {"adres": "Drontermeer 13, Amersfoort", "expected_has_charger": True},
    {"adres": "Grevelingenmeer 4, Amersfoort", "expected_has_charger": True},
    {"adres": "Grevelingenmeer 8, Amersfoort", "expected_has_charger": True},
    {"adres": "Ketelmeer 12, Amersfoort", "expected_has_charger": True},
    {"adres": "Zwarte zee 10, Amersfoort", "expected_has_charger": True},
    {"adres": "Zwarte zee 2, Amersfoort", "expected_has_charger": True},
    {"adres": "Veluwemeer 5, Amersfoort", "expected_has_charger": True},
    {"adres": "Veluwemeer 9, Amersfoort", "expected_has_charger": True},
    {"adres": "Alkemaardermeer 21, Amersfoort", "expected_has_charger": True},
    {"adres": "Alkemaardermeer 41, Amersfoort", "expected_has_charger": True},
    {"adres": "Alkemaardermeer 28, Amersfoort", "expected_has_charger": True},
    {"adres": "Alkemaardermeer 22, Amersfoort", "expected_has_charger": True},
    {"adres": "Victoriameer 155, Amersfoort", "expected_has_charger": True},
    {"adres": "Victoriameer 137, Amersfoort", "expected_has_charger": True},
    {"adres": "Victoriameer 127, Amersfoort", "expected_has_charger": True},
    {"adres": "Victoriameer 125, Amersfoort", "expected_has_charger": True},
    {"adres": "Victoriameer 121, Amersfoort", "expected_has_charger": True},
    {"adres": "Comomeer 3, Amersfoort", "expected_has_charger": True},
    {"adres": "Grenspolder 12, Amersfoort", "expected_has_charger": True},
    {"adres": "Grenspolder 37, Amersfoort", "expected_has_charger": True},
    {"adres": "Grenspolder 71, Amersfoort", "expected_has_charger": True},
    {"adres": "Grenspolder 27, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 3, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 5, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 7, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 11, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 17, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 27, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 33, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 39, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 41, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 43, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 55, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 61, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 67, Amersfoort", "expected_has_charger": True},
    {"adres": "Balatonmeer 71, Amersfoort", "expected_has_charger": True},
    {"adres": "Prepameer 2, Amersfoort", "expected_has_charger": True},
    {"adres": "Iseomeer 1, Amersfoort", "expected_has_charger": True},
    {"adres": "Adriatische zee 1a, Amersfoort", "expected_has_charger": True},
    {"adres": "Adriatische zee 1b, Amersfoort", "expected_has_charger": True},
    {"adres": "Adriatische zee 2b, Amersfoort", "expected_has_charger": True},
    {"adres": "Egeische zee 1a, Amersfoort", "expected_has_charger": True},
    {"adres": "Egeische zee 2b, Amersfoort", "expected_has_charger": True},
    {"adres": "Egeische zee 2a, Amersfoort", "expected_has_charger": True},
    {"adres": "Suzana polder 36, Amersfoort", "expected_has_charger": True},
    {"adres": "Suzana polder 34, Amersfoort", "expected_has_charger": True},
    {"adres": "Suzana polder 31, Amersfoort", "expected_has_charger": True},
    {"adres": "Suzana polder 22, Amersfoort", "expected_has_charger": True},
    {"adres": "Suzana polder 16, Amersfoort", "expected_has_charger": True},
    {"adres": "Suzana polder 4, Amersfoort", "expected_has_charger": True},
    {"adres": "Magdalenapolder 37, Amersfoort", "expected_has_charger": True},
    {"adres": "Louisapolder 25, Amersfoort", "expected_has_charger": True},
    {"adres": "Louisapolder 9, Amersfoort", "expected_has_charger": True},
    {"adres": "Azoren 1, Amersfoort", "expected_has_charger": True},
    {"adres": "Nicobaren 1, Amersfoort", "expected_has_charger": True},
    {"adres": "Nicobaren 3, Amersfoort", "expected_has_charger": True},
    {"adres": "Heideweg 60, Amersfoort", "expected_has_charger": True},
    {"adres": "Heideweg 68, Amersfoort", "expected_has_charger": True},
    {"adres": "Heideweg 68a, Amersfoort", "expected_has_charger": True},
    {"adres": "Bruinveer 10, Amersfoort", "expected_has_charger": True},
    {"adres": "Zijerveen 5, Amersfoort", "expected_has_charger": True},
    {"adres": "Zijerveen 7, Amersfoort", "expected_has_charger": True},
    {"adres": "Zijerveen 4, Amersfoort", "expected_has_charger": True},
    {"adres": "Zijerveen 11, Amersfoort", "expected_has_charger": True},
    {"adres": "Wapserveen 3, Amersfoort", "expected_has_charger": True},
    {"adres": "Heemserveen 3, Amersfoort", "expected_has_charger": True},
    {"adres": "Ermerveen 6, Amersfoort", "expected_has_charger": True},
    {"adres": "Ermerveen 5, Amersfoort", "expected_has_charger": True},
    {"adres": "Drouwenerveen 1, Amersfoort", "expected_has_charger": True},
    {"adres": "Veenslagen 45, Amersfoort", "expected_has_charger": True},
    {"adres": "Veenslagen 22, Amersfoort", "expected_has_charger": True},
    {"adres": "Veenslagen 26, Amersfoort", "expected_has_charger": True},
    {"adres": "Veenslagen 30, Amersfoort", "expected_has_charger": True},
    {"adres": "Veenslagen 59, Amersfoort", "expected_has_charger": True},
    {"adres": "Veenslagen 55, Amersfoort", "expected_has_charger": True},
    {"adres": "Amerongseweg 8, Amersfoort", "expected_has_charger": True},
    {"adres": "Aardmansweg 6, Amersfoort", "expected_has_charger": True},
    {"adres": "Bennekomseweg 10, Amersfoort", "expected_has_charger": True},
    {"adres": "Bennekomseweg 22, Amersfoort", "expected_has_charger": True},
    {"adres": "Braamberg 3, Amersfoort", "expected_has_charger": True},
    {"adres": "Braamberg 9, Amersfoort", "expected_has_charger": True},
    {"adres": "Braamberg 15, Amersfoort", "expected_has_charger": True},
    {"adres": "Braamberg 10, Amersfoort", "expected_has_charger": True},
    {"adres": "Bundersberg 10, Amersfoort", "expected_has_charger": True},
    {"adres": "Carolinabers 23, Amersfoort", "expected_has_charger": True},
    {"adres": "Carolinabers 21, Amersfoort", "expected_has_charger": True},
    {"adres": "Carolinabers 5, Amersfoort", "expected_has_charger": True},
    {"adres": "Carolinabers 7, Amersfoort", "expected_has_charger": True},
    {"adres": "Eschberg 34, Amersfoort", "expected_has_charger": True},
    {"adres": "Eschberg 36, Amersfoort", "expected_has_charger": True},
    {"adres": "Eschberg 19, Amersfoort", "expected_has_charger": True},
    {"adres": "Emminkerhuizerberg 92, Amersfoort", "expected_has_charger": True},
    {"adres": "Emminkerhuizerberg 94, Amersfoort", "expected_has_charger": True},
    {"adres": "Vijlenerberg 11, Amersfoort", "expected_has_charger": True},
    {"adres": "Vijlenerberg 17, Amersfoort", "expected_has_charger": True},
    {"adres": "Vuursteenberg 14, Amersfoort", "expected_has_charger": True},
    {"adres": "Vuursteenberg 80, Amersfoort", "expected_has_charger": True},
    {"adres": "Vuursteenberg 86, Amersfoort", "expected_has_charger": True},
    {"adres": "Kliftsberg 8, Amersfoort", "expected_has_charger": True},
    {"adres": "Sprengenberg 14, Amersfoort", "expected_has_charger": True},
    {"adres": "Sprengenberg 154, Amersfoort", "expected_has_charger": True},
    {"adres": "Sprengenberg 140, Amersfoort", "expected_has_charger": True},
    {"adres": "Bovenkerkerpolder 8, Amersfoort", "expected_has_charger": True},
    {"adres": "Bovenkerkerpolder 12, Amersfoort", "expected_has_charger": True},
    {"adres": "Bovenkerkerpolder 24, Amersfoort", "expected_has_charger": True},
    {"adres": "Bovenkerkerpolder 36, Amersfoort", "expected_has_charger": True},
    {"adres": "Bovenkerkerpolder 42, Amersfoort", "expected_has_charger": True},
    {"adres": "Bovenkerkerpolder 48, Amersfoort", "expected_has_charger": True},
    {"adres": "Bovenkerkerpolder 54, Amersfoort", "expected_has_charger": True},
    {"adres": "Bethunepolder 12, Amersfoort", "expected_has_charger": True},
]

if __name__ == '__main__':
    print(f'Totaal: {len(TEST_ADDRESSES)}')
